addpath('./data')
addpath('./utilities')
addpath('./utilities/TimeStepping')
addpath('./utilities/vectorOps')
addpath('./utilities/domainSetup')
addpath('/Users/ryanhass/Documents/MATLAB/Lele_Research/matlabFunctions')