addpath('../../utilities')
addpath('../../utilities/TimeStepping')
addpath('../../utilities/vectorOps')
addpath('../../utilities/domainSetup')
addpath('../../utilities/derivatives')
addpath('/home1/06632/ryanhass/EnrichmentProject/matlabFunctions/')
