addpath('../../utilities')
addpath('../../utilities/TimeStepping')
addpath('../../utilities/vectorOps')
addpath('../../utilities/domainSetup')
addpath('../../utilities/derivatives')
addpath('/Users/ryanhass/Documents/MATLAB/Lele_Research/matlabFunctions')